[package]
name = "ringiflow-shared"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
openapi = ["dep:utoipa"]

[dependencies]
serde.workspace = true
utoipa = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true
